#!/usr/bin/env python3
"""
One-time tool: parse extracted_all_*.txt and generate kst_test_data.h
"""

import os

SRC = os.path.join(os.path.dirname(__file__),
    "extracted_all_from_angle_test_result_2026_02_13_17_10_41_20260303_150234.txt")
DST = os.path.join(os.path.dirname(__file__), "kst_test_data.h")

entries = []
with open(SRC, "r") as f:
    for i, line in enumerate(f):
        if i == 0:  # skip header
            continue
        line = line.rstrip("\n").rstrip("\r")
        if not line:
            continue
        cols = line.split("\t")
        if len(cols) < 8:
            continue
        yaw        = float(cols[0])
        pitch      = float(cols[1])
        coords_str = cols[3]  # WriteCoords: TL_x,TL_y,TR_x,TR_y,BL_x,BL_y,BR_x,BR_y
        error_code = int(cols[6])
        coords = [int(x) for x in coords_str.split(",")]
        if len(coords) != 8:
            continue
        entries.append((yaw, pitch, *coords, error_code))

print(f"Parsed {len(entries)} entries.")

lines = []
lines.append("// Auto-generated by gen_kst_test_data.py — DO NOT EDIT MANUALLY")
lines.append("// Source: extracted_all_from_angle_test_result_2026_02_13_17_10_41_20260303_150234.txt")
lines.append("#ifndef KST_TEST_DATA_H")
lines.append("#define KST_TEST_DATA_H")
lines.append("")
lines.append("#include <cstdint>")
lines.append("")
lines.append("struct KstTestEntry {")
lines.append("    float yaw;")
lines.append("    float pitch;")
lines.append("    int16_t tl_x, tl_y, tr_x, tr_y, bl_x, bl_y, br_x, br_y;")
lines.append("    int32_t error_code;")
lines.append("};")
lines.append("")
lines.append(f"static const int KST_TEST_DATA_COUNT = {len(entries)};")
lines.append("")
lines.append("static const KstTestEntry KST_TEST_DATA[] = {")
for e in entries:
    yaw, pitch, tl_x, tl_y, tr_x, tr_y, bl_x, bl_y, br_x, br_y, error_code = e
    lines.append(
        f"    {{{yaw:.1f}f, {pitch:.1f}f, "
        f"{tl_x}, {tl_y}, {tr_x}, {tr_y}, "
        f"{bl_x}, {bl_y}, {br_x}, {br_y}, "
        f"{error_code}}},"
    )
lines.append("};")
lines.append("")
lines.append("#endif // KST_TEST_DATA_H")

with open(DST, "w") as f:
    f.write("\n".join(lines) + "\n")

print(f"Written to {DST}")
